# Generated by Django 5.1 on 2024-08-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
