# Generated by Django 5.1 on 2024-08-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_city_country_account_city_account_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.country'),
        ),
    ]
