# Generated by Django 5.1 on 2024-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
