# Generated by Django 5.1 on 2024-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_variation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='count',
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], max_length=100),
        ),
    ]
