# Generated by Django 5.1 on 2024-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_variation_count_alter_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
