# Generated by Django 5.1.1 on 2024-11-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_comments_subject_alter_comments_messsage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='messsage',
            new_name='message',
        ),
    ]
