# Generated by Django 5.1 on 2024-08-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
