# Generated by Django 5.1 on 2024-08-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/%Y/%M/%d'),
        ),
    ]
